Make all (most?) hardcoded values configurable. Add a guard for classes/objects @SideOnly'd for the other side, causing Configuration to crash through a NoClassDefFoundError. Simplify min()/max() code in RenderAOEIceSpike. Fix a hidden bug causing `RenderAOEIceSpike.model` be a MCF's TechneModel, since it's not lazy and called before overriding the TechneModelLoader. Make NBTLoadable, NBTSavable, NBTReloadable and IConfigurable value traits